# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments


# Permalinks
permalink: /blog/:year/:month/:day/:title/

# Setup
logo:             'http://i.imgur.com/SyxoguR.png'
title:            MASSIS
tagline:          'A Jekyll theme'
description:      'A Framework for MultiAgent System Simulation of Indoor Scenarios'
baseurl:           /MASSIS

sidebar:
- url: /
  text: Home

- url: /getting-started.html
  text: Getting started
  
- url: /tutorials/
  text: Tutorials


# Por ahora no tenemos blog
#- url: /blog/
#  text: Blog


author:
  name:           'Rafael Pax and Juan Pav&oacute;n (UCM GRASIA)'
  url:            http://www.massisframework.com/


# Custom vars
version:          1.2.10

github:
  repo:           https://github.com/rpax/MASSIS

collections:
    tutorials:
        output: true

defaults:
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial

exclude: 
  - Gemfile 
  - Gemfile.lock 
  - LICENSE 
  - README.md 
  - CNAME
    


